app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /documentation

# Auth-tokens
auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

# User
users:
    type:     rest
    resource: AppBundle\Controller\UserController

# Position
position:
    type:     rest
    resource: AppBundle\Controller\Position\PositionController

# Product Position
product_position:
    type:     rest
    resource: AppBundle\Controller\Product\ProductPositionController

# Order
order:
    type:     rest
    resource: AppBundle\Controller\Order\OrderController

# Order Product
order_product:
    type:     rest
    resource: AppBundle\Controller\Order\OrderProductController
