app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /documentation

# Auth-tokens
auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

# User
users:
    type:     rest
    resource: AppBundle\Controller\UserController

# Position
position:
    type:     rest
    resource: AppBundle\Controller\Position\PositionController

# Product Position
product_position:
    type:     rest
    resource: AppBundle\Controller\Product\ProductPositionController

# Order
order:
    type:     rest
    resource: AppBundle\Controller\Order\OrderController

# Order Product
order_product:
    type:     rest
    resource: AppBundle\Controller\Order\OrderProductController

# Couple
couple:
    type:     rest
    resource: AppBundle\Controller\Couple\CoupleController

# Preparation
preparation:
    type:     rest
    resource: AppBundle\Controller\Preparation\PreparationController

# User Caracteristic
user_caracteristic:
    type:     rest
    resource: AppBundle\Controller\User\UserCaracteristicController


# Course
course:
    type:     rest
    resource: AppBundle\Controller\Course\CourseController