AppBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'auth-token', 'preparation']
        identifier:
            groups: ['user', 'auth-token']
        firstname:
            groups: ['user', 'auth-token', 'preparation']
        lastname:
            groups: ['user', 'auth-token', 'preparation']
        email:
            groups: ['user', 'auth-token']
        username:
            groups: ['user', 'auth-token']
        caracteristic:
            groups: ['user']
