AppBundle\Entity\Preparation\Preparation:
    exclusion_policy: none
    properties:
        id:
            groups: ['preparation', 'course']
        user:
            groups: ['preparation']
        startTime:
            groups: ['preparation']
        endTime:
            groups: ['preparation']
        orders:
            groups: ['preparation']
        courses:
            groups: ['preparation']
