AppBundle\Entity\Course\Course:
    exclusion_policy: none
    properties:
        id:
            groups: ['course']
        preparation:
            groups: ['course']
        productPosition:
            groups: ['course']
        stepValidated:
            groups: ['course']
        quantity:
            groups: ['course']
