AppBundle\Entity\Course\Course:
    exclusion_policy: none
    properties:
        id:
            groups: ['course', 'preparation']
        preparation:
            groups: ['course', 'preparation']
        productPosition:
            groups: ['course', 'preparation']
        stepValidated:
            groups: ['course', 'preparation']
        quantity:
            groups: ['course', 'preparation']
