AppBundle\Entity\Product\ProductPosition:
    exclusion_policy: none
    properties:
        id:
            groups: ['product-position', 'course']
        position:
            groups: ['product-position', 'course']
        product:
            groups: ['product-position', 'course']
        quantity:
            groups: ['product-position', 'course']
