AppBundle\Entity\Product\Product:
    exclusion_policy: none
    properties:
        id:
            groups: ['product', 'notification', 'preparation', 'preparation']
        ean13:
            groups: ['product', 'course', 'notification']
        description:
            groups: ['product', 'course']
        price:
            groups: ['product']
        weight:
            groups: ['product', 'course']
        orders:
            groups: ['product']
        positions:
            groups: ['product']
